categories:
  - title: 'Breaking'
    label: 'breaking'
  - title: 'New'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Maintenance'
    label: 'maintenance'
  - title: 'Documentation'
    label: 'docs'
  - title: 'Dependency Updates'
    label: 'dependencies'
autolabeler:
  - label: 'chore'
    title:
      - '/chore[:]/i'
  - label: 'bug'
    title:
      - '/fix[:]/i'
  - label: 'enhancement'
    title:
      - '/feat[:]/i'
template: |
  # What's Changed
  $CHANGES

