name: Merge On Approve

on:
  pull_request_review:
    types: [submitted]
  push: 
    branches: drgf

jobs:
  approved:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh pr merge ${{github.event.pull_request.html_url}} --merge
        
