on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved' && github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - run: gh pr merge ${{ github.event.pull_request.number }} --merge
