on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved' && github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh pr merge --merge
        
