name: Release Publisher

on:
  workflow_run:
    workflows: ["Merge On Approve"]
    types:
      - completed
  #push:
    # branches to consider in the event; optional, defaults to all
    #branches: 
    #  - master

jobs:
  publish_release_draft:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        
      - name: Make Tag
        uses: actions/github-script@v5
        env: 
          TAG: ${{ steps.previoustag.outputs.tag }}
        id: tag-script
        with:
          result-encoding: string
          script: |
            const { TAG } = process.env
            let today = new Date()
            var re = new RegExp('-', 'g')
            var tpo = today.toISOString().split('T')[0].replace(re,"")
            var fullTag = TAG.split('.')
            if (fullTag[0] == tpo)
            {
              var inter = parseInt(fullTag[1]) + 1
              console.log(fullTag[0]+"."+inter)
              return fullTag[0]+"."+inter
            }
            else
            {
              console.log(tpo+".0")
              return tpo+".0"
            }
          
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Draft Release 
        uses: release-drafter/release-drafter@v5
        with:
          tag: "${{ steps.tag-script.outputs.result }}"
          name: "${{ steps.tag-script.outputs.result }}"
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
